application/auth.py
"""Routes for user authentication."""
from flask import redirect, render_template, flash, Blueprint, request, url_for
from flask_login import login_required, logout_user, current_user, login_user
from flask import current_app as app
from werkzeug.security import generate_password_hash
#from .assets import compile_auth_assets
from .forms import LoginForm, SignupForm
from .models import db, User
from .import login_manager


# Blueprint Configuration
auth_bp = Blueprint('auth_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
#compile_auth_assets(app)

#@auth_bp.route('/')
#def main_page():
#    return flask.render_template('main_page.html')


@auth_bp.route('/login', methods=['GET', 'POST'])
def login_page():
    """User login page."""
    # Bypass Login screen if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))
    login_form = LoginForm(request.form)
    # POST: Create user and redirect them to the app
    if request.method == 'POST':
        if login_form.validate():
            # Get Form Fields
            email = request.form.get('email')
            password = request.form.get('password')
            # Validate Login Attempt
            user = User.query.filter_by(email=email).first()
            if user:
                if user.check_password(password=password):
                    login_user(user)
                    next = request.args.get('next')
                    return redirect(next or url_for('main_bp.dashboard'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login_page'))
    # GET: Serve Log-in page
    return render_template('login.html',
                           form=LoginForm(),
                           title='Log in | Flask-Login Tutorial.',
                           template='login-page',
                           body="Log in with your User account.")


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup_page():
    """User sign-up page."""
    signup_form = SignupForm(request.form)
    # POST: Sign user in
    if request.method == 'POST':
        if signup_form.validate():
            # Get Form Fields
            name = request.form.get('name')
            email = request.form.get('email')
            password = request.form.get('password')
            existing_user = User.query.filter_by(email=email).first()
            if existing_user is None:
                user = User(name=name,
                            email=email,
                            password=generate_password_hash(password, method='sha256'))
                db.session.add(user)
                db.session.commit()
                login_user(user)
                return redirect(url_for('main_bp.dashboard'))
                #return redirect(url_for('auth_bp.login_page'))
            flash('A user already exists with that email address.')
            return redirect(url_for('auth_bp.signup_page'))
    # GET: Serve Sign-up page
    return render_template('/signup.html',
                           title='Create an Account | Flask-Login Tutorial.',
                           form=SignupForm(),
                           template='signup-page',
                           body="Sign up for a user account.")


@auth_bp.route("/logout")
@login_required
def logout_page():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login_page'))


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None
@auth_bp.route("/about_us")
def about_us():
    return render_template('about_us.html')


@login_manager.unauthorized_handler
def unauthorized():
    return render_template('main_page.html')
    """Redirect unauthorized users to Login page."""
    #flash('You must be logged in to view that page.')
    #return redirect(url_for('auth_bp.main_page'))

application/routes.py
"""Routes for logged-in application."""
from flask import Blueprint, render_template
from flask_login import current_user
from flask import current_app as app
#from .assets import compile_auth_assets
from flask_login import login_required
import os
import numpy as np
import flask
import pickle
from flask import Flask, render_template, request
import pandas as pd
import io
import csv
from flask import json
from flask import Response
#from sklearn.preprocessing import MinMaxScaler
#from sklearn.metrics import mean_squared_error
import numpy as np
import pickle
from keras.models import load_model

#from sklearn.metrics import mean_absolute_error
#from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
#from matplotlib.figure import Figure
import random
#from matplotlib import pyplot as plt
import io
#import seaborn as sns
from flask import Flask, render_template, request
from werkzeug import secure_filename
from flask import send_from_directory
import os
from flask import make_response
from functools import wraps, update_wrapper
import datetime
from datetime import timedelta
"""Routes for user authentication."""
from flask import redirect, render_template, flash, Blueprint, request, url_for
from flask_login import login_required, logout_user, current_user, login_user
from flask import current_app as app
from werkzeug.security import generate_password_hash
#from .assets import compile_auth_assets
from .forms import LoginForm, SignupForm
from .models import db, User,Score 
from .import login_manager



# Blueprint Configuration
main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
#compile_auth_assets(app)




@main_bp.route('/', methods=['GET'])
@login_required
def dashboard():
    """Serve logged in Dashboard."""
    return render_template('csv.html',
                           title='Flask-Login Tutorial.',
                           template='dashboard-template',
                           current_user=current_user,
                           body="You are now logged in!")



def features(segment_1):
    for i in range(len(segment_1)):
        for j in range(len(segment_1[i])):
            x = segment_1[i][j]
            segment_1[i][j]=x
        segment_1[i]=segment_1[i]+[0]*(129-len(segment_1[i]))
    return segment_1


@main_bp.route('/home', methods=['GET','POST'])
#@app.route('/home',methods= ['GET','POST'])
def read_csv():
    if request.method=="POST":
        if request.files.get("txt",None) is not None: 
            f=request.files["txt"]
            f.save(secure_filename('hello.txt'))
            data=pd.read_csv('hello.txt')
            data = data[data.S != 'T001']   
            data = data[data.S != 'T002']
            data = data[data.S != 'T003']
            data = data[data.S != 'T004']
            data = data[data.S != 'T005']
            data = data[data.S != 'M020']  
            data = data[data.S != 'M007']
            data = data[data.S != 'M019']
            data = data[data.S != 'M027']
            ep_seg = data.copy()
            ep_seg = ep_seg[ep_seg.S != 'D001']
            ep_seg = ep_seg[ep_seg.S != 'D002']
            ep_seg = ep_seg[ep_seg.S != 'D004']
            ep_seg = ep_seg[ep_seg.S != 'LEAVEHOME']
            ep_seg = ep_seg[ep_seg.S != 'ENTERHOME']
            ep_seg = ep_seg[ep_seg.S != 'c']
            ep_seg = ep_seg[ep_seg.M != 'OFFc']
            ep_seg = ep_seg[ep_seg.M != 'ONc']
            ep_seg = ep_seg[ep_seg.M != 'ON5']
            ep_seg = ep_seg[ep_seg.M != 'OFF5']
            ep_seg = ep_seg[ep_seg.M != 'ONcc']
            ep_seg = ep_seg[ep_seg.M != 'OFF5c']
            ep_seg = ep_seg[ep_seg.M != 'ON5c']
            ep_seg = ep_seg[ep_seg.M != 'OFFcc']
            ep_seg = ep_seg[ep_seg.M != 'OFFc5']
            ep_seg = ep_seg[ep_seg.M != 'ONc5']
            ep_seg = ep_seg[ep_seg.M != 'OFcF']
            ep_seg = ep_seg[ep_seg.M != 'ONc5c']
            ep_seg = ep_seg[ep_seg.M != 'ONM024']
            ep_seg = ep_seg[ep_seg.M != 'ON55']
            ep_seg = ep_seg[ep_seg.M != 'OFF5cc']
            ep_seg = ep_seg[ep_seg.M != 'ONM026']
            ep_seg = ep_seg[ep_seg.M != 'OFFccc5']
            ep_seg = ep_seg[ep_seg.M != 'ONM009']
            ep_seg = ep_seg[ep_seg.M != 'O']
            ep_seg1 = ep_seg.copy()
            ep_seg1 = ep_seg[ep_seg1.M != 'OFF']
            ep_segt=list(ep_seg1.Time)
            ep_segs=list(ep_seg1.S)
            num1={}
            num1[0]=0
            num1['M001']=1
            num1['M002']=2
            num1['M003']=3
            num1['M004']=4
            num1['M005']=5
            num1['M006']=6
            num1['M007']=7
            num1['M008']=8
            num1['M009']=9
            num1['M010']=10
            num1['M011']=11
            num1['M012']=12
            num1['M013']=13
            num1['M014']=14
            num1['M015']=15
            num1['M016']=16
            num1['M017']=17
            num1['M018']=18
            num1['M019']=19
            num1['M020']=20
            num1['M021']=21
            num1['M022']=22
            num1['M023']=23
            num1['M024']=24
            num1['M025']=25
            num1['M026']=26
            num1['M027']=27
            num1['M028']=28
            num1['M029']=29
            num1['M030']=30
            num1['M031']=31 
            for i in range(len(ep_segt)):
                data_pre = ep_segt[i].strip().split(',')
                stDate = data_pre[0].replace("\"", "")
                #print ("stDate before: ", stDate)
                try:
                    dat_time = datetime.datetime.strptime(stDate,
                               '%H:%M:%S.%f')                                  
                except:
                    stDate = stDate + ".4"
                    dat_time = datetime.datetime.strptime(stDate,'%H:%M:%S.%f')
                    ep_segt[i] = stDate
            
            segment = []
            new = []
            new.append(ep_segs[0])
            f=0
            prev_time =  '00:03:50.209589'
            datetimeFormat = '%H:%M:%S.%f'

            for i in range(1,len(ep_seg1)):
                diff = datetime.datetime.strptime(ep_segt[i], datetimeFormat) - datetime.datetime.strptime(prev_time, datetimeFormat)
                prev_time = ep_segt[i]
                if diff.seconds > 10 or (ep_segs[i-1]==ep_segs[i]):
                    if(len(new)>0):
                        segment.append(new)
                        E = []
                        E.append(ep_segs[i])
                        new = E
                else:
                    new.append(ep_segs[i])    
            if(len(new)>0):
                segment.append(new)    
            l=[segment[i] for i in range(len(segment)) if len(segment[i])<=32 and len(segment[i])>3]
            l=features(l)
            h=[]
            for i in range(len(l)):
                k=[]
                for j in range(len(l[i])):
                    k.append(num1[l[i][j]])
                h.append(k)
            l=h 
            l=np.asarray(l)
            l=np.reshape(l,(l.shape[0],l.shape[1],1))
            #l=[[num1[i] for i in x] for x in l]
            model = load_model('model.hdf5')
            t=model.predict(l)
            h=t.argmax(axis=-1)
            c=0
            for i in h:
                if i==0:
                    c+=1
            g=(c*1.0/len(h))*100.0
            email=current_user.email
            score= Score(email=email,result=g)
            db.session.add(score)
            db.session.commit()
            #email=current_user.email
            #score= Score.query.filter_by(email=email).first()
            #score.objects().all()
            return flask.render_template('result.html',listt=g)


@main_bp.route('/history', methods=['GET','POST'])
def history():
    if request.method=="GET":
            email=current_user.email
            score= Score.query.filter_by(email=email)
            y=list()
            for x in score:
                y.append(x.result)
            return flask.render_template('history.html',history=y)

application/templates/about_us.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Bungee|Bungee+Shade|Covered+By+Your+Grace" rel="stylesheet">
<style>
body, html {
  height: 100%;
  margin: 0;
}
body {
  /* The image used */
  background-image: url("static/cool.png");

  /* Full height */
  height: 100%; 


  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
body {
  font-family: Roboto;
  background: #005aa7;
  /* fallback for old browsers */
  background: -webkit-linear-gradient(to left, #005aa7, #fffde4);
  /* Chrome 10-25, Safari 5.1-6 */
  background: linear-gradient(to left,#005aa7, #fffde4
    );
  color: black;
  /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}
.para{
 font-size: 2em; 
}
</style>	
</head>
<body>

<h1>Hello</h1>
</body>
</html>

application/templates/about_us.html.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Bungee|Bungee+Shade|Covered+By+Your+Grace" rel="stylesheet">
<style>
body, html {
  height: 100%;
  margin: 0;
}
body {
  /* The image used */
  background-image: url("static/cool.png");

  /* Full height */
  height: 100%; 


  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
body {
  font-family: Roboto;
  background: #005aa7;
  /* fallback for old browsers */
  background: -webkit-linear-gradient(to left, #005aa7, #fffde4);
  /* Chrome 10-25, Safari 5.1-6 */
  background: linear-gradient(to left,#005aa7, #fffde4
    );
  color: black;
  /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}
.para{
 font-size: 2em; 
}
</style>	
</head>
<body>

<p class="para"><b><a href="{{ url_for('main_bp.dashboard') }}" target="_self">Home</a></b></p>
<div class="container">
<div class="page-header">
<h1>{{ 100-listt }} % chances of dementia</h1>
{% if result==1 %}
<h2>YOU MAY HAVE DEMENTIA.CONSULT A DOCTOR IMMEDIATELY.</h2>
</div>
{% else %}
<h2>EVERYTHING LOOKS FINE</h2>
{% endif %}
</div>
</div>
</body>
</html>

application/templates/csv.html
<!DOCTYPE html>
<html>
<div class="card-panel teal lighten-2">
<head>
<title>UPLOAD DATA</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Bungee|Bungee+Shade|Covered+By+Your+Grace" rel="stylesheet">

<style>
body, html {
  height: 100%;
  margin: 0;
}



h1   {color: red;}
p    {color: red;}

body {
  /* The image used */

  /* Full height */
  height: 100%; 


  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
body {
  font-family: Roboto;
  background: #000000;
  /* fallback for old browsers */
  background: -webkit-linear-gradient(to left, #000000, #434343);
  /* Chrome 10-25, Safari 5.1-6 */
  background: linear-gradient(to left, #000000, #434343);
  /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}
input[type=file] {
  width: 100%;
  padding: 0;
  margin: 200 auto;
  margin-right:-2px;
  box-sizing: border-box;
  color: white;
    font-size: 1em;
}

input[type=submit] {
  width: 50%;
  padding:0;
  box-sizing: border-box;
    font-size: 1em;
    
}
body {
    text-align: center;
}
div.form
{
    display: block;
    text-align: center;
}
form
{
    display: inline-block;
    margin-left: auto;
    margin-right: auto;
    text-align: left;
}

input[type=file] {
    display: inline;
    height: 35px;
    margin: 200 auto;
    margin-right:-2px;
    font-size: 2em;
}
input[type=submit] {
    display: inline;
    height: 35px;
    background-color: #63beb5;
    border: none;
    margin: 0;
    text-transform: uppercase;
    color: #fff;
    font-size: 2em;
    padding-left: 10px;
    padding-right: 10px;
}
body {
  /* The image used */
  background-image: url('static/dist/img/b2.jpg');

  /* Full height */
  height: 100%; 


  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}



</style>	</head>
<!--<link rel="stylesheet" href='static/dist/css/style.css'>
<script type="text/javascript" src='static/src/js/particles.js'></script>
  <script type="text/javascript" src='static/src/js/app.js'></script>-->


<body>
<div id="particles-js"></div>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
        <div class="navbar-header">
      <a class="navbar-brand" href="#">Hi {{ current_user.name }}!</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{{ url_for('auth_bp.logout_page') }}">Logout</a></li>
      <li class="active"><a href="{{ url_for('main_bp.history') }}" >History</a></li>
    </ul>
  </div>
</nav>
<!--{% block content %}
    <h1>{{body}}</h1>

    {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('auth_bp.logout_page') }}">Log out</a>
  {% endif %}
{% endblock %}-->

<div class="container">
<div class="form">
<form action="{{ url_for('main_bp.read_csv') }}" method="POST" enctype=multipart/form-data>
<div class="form-group">
<input type="file" name="txt" id="txtFileUpload" accept=".txt"/></div>
<input type="submit" class="btn" value="Upload" >
</form>
</div>
</div>
</body>
</div>
</html>

application/templates/dashboard.html
{% extends "layout.html" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
    <h1>{{body}}</h1>

    {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('auth_bp.logout_page') }}">Log out</a>
  {% endif %}
{% endblock %}

application/templates/gu.html
<!DOCTYPE html>
<html>
<div class="card-panel teal lighten-2">
<head>
<title>UPLOAD DATA</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Bungee|Bungee+Shade|Covered+By+Your+Grace" rel="stylesheet">
<style>
// Colors
$text: white;
$link: #e34234;
$link-hover: #ba160c;

canvas {
  display: block;
  vertical-align: bottom;
}

#particles-js {
  position: absolute;
  width: 100%;
  height: 100%;
  background: {
      image: url(https://marcbruederlin.github.io/particles.js/img/background.jpg);
      position: bottom;
      repeat: no-repeat;
      color: black;
      size: cover;
  }
}

.text {
	position: absolute;
	top: 50%;
	right: 50%;
	transform: translate(50%,-50%);
	color: $text;
	max-width: 90%;
	padding: 2em 3em;
	background: rgba(0, 0, 0, 0.75);
	text-shadow: 0px 0px 2px #131415;
	font-family: 'Open Sans', sans-serif;
}

h1 {
	font-size: 2.25em;
	font-weight: 700;
	letter-spacing: -1px;
}

a,
a:visited {
	color: $link;
	transition: 0.25s;
}

a:hover,
a:focus {
	color: $link-hover;
}</style>
</head></div>
<body>
<div id="particles-js"></div>

<div class="text">
	<h1>Particles Background-Image</h1>
	<p>Using <a href="https://github.com/VincentGarreau/particles.js/">ParticlesJS</a> and well...</p>
</div></body>
<script>
	var color = '#75A5B7';
var maxParticles = 80;

// ParticlesJS Config.
particlesJS('particles-js', {
  'particles': {
    'number': {
      'value': maxParticles,
      'density': {
        'enable': true,
        'value_area': (maxParticles * 10) * 2
      }
    },
    'color': {
      'value': color
    },
    'shape': {
      'type': 'circle',
      'stroke': {
        'width': 0,
        'color': '#000000'
      },
      'polygon': {
        'nb_sides': 5
      },
    },
    'opacity': {
      'value': 0.5,
      'random': false,
      'anim': {
        'enable': false,
        'speed': 1,
        'opacity_min': 0.1,
        'sync': false
      }
    },
    'size': {
      'value': 3,
      'random': true,
      'anim': {
        'enable': false,
        'speed': 40,
        'size_min': 0.1,
        'sync': false
      }
    },
    'line_linked': {
      'enable': true,
      'distance': 150,
      'color': color,
      'opacity': 1,
      'width': 1
    },
    'move': {
      'enable': true,
      'speed': 2,
      'direction': 'none',
      'random': false,
      'straight': false,
      'out_mode': 'out',
      'bounce': false,
      'attract': {
        'enable': false,
        'rotateX': 600,
        'rotateY': 1200
      }
    }
  },
  'interactivity': {
    'detect_on': 'canvas',
    'events': {
      'onhover': {
        'enable': true,
        'mode': 'grab'
      },
      'onclick': {
        'enable': true,
        'mode': 'push'
      },
      'resize': true
    },
    'modes': {
      'grab': {
        'distance': 140,
        'line_linked': {
          'opacity': 1
        }
      },
      'bubble': {
        'distance': 400,
        'size': 40,
        'duration': 2,
        'opacity': 8,
        'speed': 3
      },
      'repulse': {
        'distance': 200,
        'duration': 0.4
      },
      'push': {
        'particles_nb': 4
      },
      'remove': {
        'particles_nb': 2
      }
    }
  },
  'retina_detect': true
});</script>
</html>


  margin: 0 auto;
    display: inline;
    margin-right: 50%;
    margin-top: 10%



    login
     margin: 0 auto;
  margin-top:600px;
  margin-left:60px;

application/templates/history.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Bungee|Bungee+Shade|Covered+By+Your+Grace" rel="stylesheet">
<style>
body, html {
  height: 100%;
  margin: 0;
}
body {
  /* The image used */
  background-image: url("static/cool.png");

  /* Full height */
  height: 100%; 


  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
body {
  font-family: Roboto;
  background: #005aa7;
  /* fallback for old browsers */
  background: -webkit-linear-gradient(to left, #005aa7, #fffde4);
  /* Chrome 10-25, Safari 5.1-6 */
  background: linear-gradient(to left,#005aa7, #fffde4
    );
  color: black;
  /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}
.para{
 font-size: 2em; 
}
body {
  /* The image used */
  background-image: url('static/dist/img/cool.png');

  /* Full height */
  height: 100%; 


  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>	
</head>
<body>
  <div class="container">
<div class="page-header">
<ul class="list-group">
{% for i in history %}
<li class="list-group-item">{{ 100-i }}</li>
{% endfor %}
</ul>
</div>
</div>
</body>
</html>

application/templates/main_page.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Bungee|Bungee+Shade|Covered+By+Your+Grace" rel="stylesheet">
<style>
body, html {
  height: 100%;
  margin: 0;
}
body {
  /* The image used */
  background-image: url("static/cool.png");

  /* Full height */
  height: 100%; 


  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
body {
  font-family: Roboto;
  background: #005aa7;
  /* fallback for old browsers */
  background: -webkit-linear-gradient(to left, #005aa7, #fffde4);
  /* Chrome 10-25, Safari 5.1-6 */
  background: linear-gradient(to left,#005aa7, #fffde4
    );
  color: black;
  /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
}
.para{
 font-size: 2em; 
}
body {
  /* The image used */
  background-image: url('static/dist/img/b2.jpg');

  /* Full height */
  height: 100%; 


  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
#login {
  padding: 10px;
  transition: transform .2s;
  width: 60px;
  height: 40px;
     position:absolute;
    transition: .5s ease;
    top: 80%;
    left: 10%;


}

#login:hover {
  -ms-transform: scale(1.5); /* IE 9 */
  -webkit-transform: scale(1.5); /* Safari 3-8 */
  transform: scale(1.5); 
}
#about {
  padding: 10px;
  transition: transform .2s;
  width: 60px;
  height: 40px;
    position:absolute;
    transition: .5s ease;
    top: 80%;
    left: 80%;


}

#about:hover {
  -ms-transform: scale(1.5); /* IE 9 */
  -webkit-transform: scale(1.5); /* Safari 3-8 */
  transform: scale(1.5); 
}
</style>	
</head>
<body>
<a class="btn btn-default" href="{{ url_for('auth_bp.login_page') }}" id="login">Login</a>
<a class="btn btn-default" href="{{ url_for('auth_bp.about_us') }}" id="about">About</a>
  </body>
  </html>